/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCreateCompanyRouteRouteImport } from './routes/_auth/create-company/route'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthCreateCompanyIndexRouteImport } from './routes/_auth/create-company/index'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAppContractsIndexRouteImport } from './routes/_auth/app/contracts/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCreateCompanyRouteRoute = AuthCreateCompanyRouteRouteImport.update({
  id: '/create-company',
  path: '/create-company',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCreateCompanyIndexRoute = AuthCreateCompanyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthCreateCompanyRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppContractsIndexRoute = AuthAppContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/create-company': typeof AuthCreateCompanyRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/create-company/': typeof AuthCreateCompanyIndexRoute
  '/app/contracts/': typeof AuthAppContractsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/create-company': typeof AuthCreateCompanyIndexRoute
  '/app/contracts': typeof AuthAppContractsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_auth/create-company': typeof AuthCreateCompanyRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/create-company/': typeof AuthCreateCompanyIndexRoute
  '/_auth/app/contracts/': typeof AuthAppContractsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/create-company'
    | '/api/auth/$'
    | '/app/'
    | '/create-company/'
    | '/app/contracts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/auth/$' | '/app' | '/create-company' | '/app/contracts'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/app'
    | '/_auth/create-company'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_auth/create-company/'
    | '/_auth/app/contracts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/create-company': {
      id: '/_auth/create-company'
      path: '/create-company'
      fullPath: '/create-company'
      preLoaderRoute: typeof AuthCreateCompanyRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/create-company/': {
      id: '/_auth/create-company/'
      path: '/'
      fullPath: '/create-company/'
      preLoaderRoute: typeof AuthCreateCompanyIndexRouteImport
      parentRoute: typeof AuthCreateCompanyRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/contracts/': {
      id: '/_auth/app/contracts/'
      path: '/contracts'
      fullPath: '/app/contracts/'
      preLoaderRoute: typeof AuthAppContractsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
  }
}

interface AuthAppRouteRouteChildren {
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppContractsIndexRoute: typeof AuthAppContractsIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppContractsIndexRoute: AuthAppContractsIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthCreateCompanyRouteRouteChildren {
  AuthCreateCompanyIndexRoute: typeof AuthCreateCompanyIndexRoute
}

const AuthCreateCompanyRouteRouteChildren: AuthCreateCompanyRouteRouteChildren =
  {
    AuthCreateCompanyIndexRoute: AuthCreateCompanyIndexRoute,
  }

const AuthCreateCompanyRouteRouteWithChildren =
  AuthCreateCompanyRouteRoute._addFileChildren(
    AuthCreateCompanyRouteRouteChildren,
  )

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
  AuthCreateCompanyRouteRoute: typeof AuthCreateCompanyRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
  AuthCreateCompanyRouteRoute: AuthCreateCompanyRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
