/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAppSettingsIndexRouteImport } from './routes/_auth/app/settings/index'
import { Route as AuthAppInvoicesIndexRouteImport } from './routes/_auth/app/invoices/index'
import { Route as AuthAppDashboardIndexRouteImport } from './routes/_auth/app/dashboard/index'
import { Route as AuthAppContractsIndexRouteImport } from './routes/_auth/app/contracts/index'
import { Route as AuthAppCashflowIndexRouteImport } from './routes/_auth/app/cashflow/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppSettingsIndexRoute = AuthAppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppInvoicesIndexRoute = AuthAppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppDashboardIndexRoute = AuthAppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppContractsIndexRoute = AuthAppContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppCashflowIndexRoute = AuthAppCashflowIndexRouteImport.update({
  id: '/cashflow/',
  path: '/cashflow/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/app/cashflow/': typeof AuthAppCashflowIndexRoute
  '/app/contracts/': typeof AuthAppContractsIndexRoute
  '/app/dashboard/': typeof AuthAppDashboardIndexRoute
  '/app/invoices/': typeof AuthAppInvoicesIndexRoute
  '/app/settings/': typeof AuthAppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/app/cashflow': typeof AuthAppCashflowIndexRoute
  '/app/contracts': typeof AuthAppContractsIndexRoute
  '/app/dashboard': typeof AuthAppDashboardIndexRoute
  '/app/invoices': typeof AuthAppInvoicesIndexRoute
  '/app/settings': typeof AuthAppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/app/cashflow/': typeof AuthAppCashflowIndexRoute
  '/_auth/app/contracts/': typeof AuthAppContractsIndexRoute
  '/_auth/app/dashboard/': typeof AuthAppDashboardIndexRoute
  '/_auth/app/invoices/': typeof AuthAppInvoicesIndexRoute
  '/_auth/app/settings/': typeof AuthAppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/api/auth/$'
    | '/app/'
    | '/app/cashflow/'
    | '/app/contracts/'
    | '/app/dashboard/'
    | '/app/invoices/'
    | '/app/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/app'
    | '/app/cashflow'
    | '/app/contracts'
    | '/app/dashboard'
    | '/app/invoices'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/app'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_auth/app/cashflow/'
    | '/_auth/app/contracts/'
    | '/_auth/app/dashboard/'
    | '/_auth/app/invoices/'
    | '/_auth/app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/settings/': {
      id: '/_auth/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AuthAppSettingsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/invoices/': {
      id: '/_auth/app/invoices/'
      path: '/invoices'
      fullPath: '/app/invoices/'
      preLoaderRoute: typeof AuthAppInvoicesIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/dashboard/': {
      id: '/_auth/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AuthAppDashboardIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/contracts/': {
      id: '/_auth/app/contracts/'
      path: '/contracts'
      fullPath: '/app/contracts/'
      preLoaderRoute: typeof AuthAppContractsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/cashflow/': {
      id: '/_auth/app/cashflow/'
      path: '/cashflow'
      fullPath: '/app/cashflow/'
      preLoaderRoute: typeof AuthAppCashflowIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
  }
}

interface AuthAppRouteRouteChildren {
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppCashflowIndexRoute: typeof AuthAppCashflowIndexRoute
  AuthAppContractsIndexRoute: typeof AuthAppContractsIndexRoute
  AuthAppDashboardIndexRoute: typeof AuthAppDashboardIndexRoute
  AuthAppInvoicesIndexRoute: typeof AuthAppInvoicesIndexRoute
  AuthAppSettingsIndexRoute: typeof AuthAppSettingsIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppCashflowIndexRoute: AuthAppCashflowIndexRoute,
  AuthAppContractsIndexRoute: AuthAppContractsIndexRoute,
  AuthAppDashboardIndexRoute: AuthAppDashboardIndexRoute,
  AuthAppInvoicesIndexRoute: AuthAppInvoicesIndexRoute,
  AuthAppSettingsIndexRoute: AuthAppSettingsIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
